theme: minima
title: Grandiose GitHub Page
author: Aelindara
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Das ist ein Test

# social links
twitter_username: aelindara 
github_username:  Aelindara
show_excerpts: true # set to false to remove excerpts on the homepage
